#!/bin/bash -e
set -euo pipefail

echo "+++ Packaging Lambda@edge"
aws --profile ${AWS_USER_NAME}  cloudformation package \
    --template-file template.yml \
    --output-template-file packaged.yaml \
    --s3-bucket ${LAMBDA_STORAGE_BUCKET} \
    --region us-east-1 

echo "+++ Deploying Lambda@Edge"
aws \
    --profile ${AWS_USER_NAME} \
    cloudformation deploy \
    --template-file packaged.yaml \
    --stack-name lambda-edge \
    --capabilities CAPABILITY_IAM \
    --region us-east-1
